#ifndef GLOBALVARIABLES_H
#define GLOBALVARIABLES_H

#define MAZE_WIDTH 672
#define MAZE_HEIGHT 864

#define HEADER_SCREEN_WIDTH 672
#define HEADER_SCREEN_HEIGHT 96

#define TOTAL_SCREEN_WIDTH 672
#define TOTAL_SCREEN_HEIGHT (MAZE_HEIGHT + HEADER_SCREEN_HEIGHT)

#define MAZE_WIDTH_IN_ARRAY 21
#define MAZE_HEIGHT_IN_ARRAY 27

#define CELL_SIZE 32
#define PACMAN_SIZE 14

#define ANIMATION_SPEED 15
#define GAME_FRAMERATE 300.0
#define DELAY 1.0 / GAME_FRAMERATE * 1000

#endif //GLOBALVARIABLES_H
