#ifndef GLOBALVARIABLES_H
#define GLOBALVARIABLES_H

#define MAZE_WIDTH 672
#define MAZE_HEIGHT 864
#define MAZE_WIDTH_IN_ARRAY 21
#define MAZE_HEIGHT_IN_ARRAY 27

#define CELL_SIZE 32
#define PACMAN_SIZE 14

#endif //GLOBALVARIABLES_H
